;; thanks to https://github.com/burke/color-theme-ir-black
;; and https://github.com/mig/color-theme-vibrant-ink

(require 'color-theme)
(defun color-theme-vibi ()
  (interactive)

  (let* ((vibrant-bg		"#000000")
         (vibrant-bg-1		"#111111")
         (vibrant-bg-2		"#222222")

         (vibrant-fg             "#FFFFFF")
         (vibrant-fg-1           "#555555")
         (vibrant-fg-2           "#7C7C7C")

         (vibrant-red		"#ff6600")
         (vibrant-red-1		"#bf4c00")

         (vibrant-yellow        "#ffcc00")
         (vibrant-yellow-1	"#ffffb6")

         (vibrant-green		"#66ff00")
         (vibrant-green-1	"#337f00")

         (vibrant-blue		"#339999")
         (vibrant-blue-1       	"#aaccff")


         (vibrant-purple	"#9933cc")
         (vibrant-purple-1	"#c859ff")

         (*normal*       vibrant-fg)
         (*background*   vibrant-bg)
         (*cursor*       vibrant-fg-1)
         (*mouse*        vibrant-fg-1)
         (*region*       vibrant-purple)
         (*current-line* vibrant-bg-1)
         (*string*       vibrant-green)
         (*keyword*      vibrant-red)
         (*method*       vibrant-yellow)
         (*comment*      vibrant-fg-2)
         (*constant*     vibrant-blue)
         (*red*          vibrant-red)
         (*operator*     vibrant-fg-1)
         (*class*        vibrant-yellow-1)
         (*variable*     vibrant-blue-1))

    (flet ((color (fgcolor &optional (bgcolor nil) (bold nil) (italic nil) (underline nil))
                  `((t (,@(if fgcolor   `(:foreground ,fgcolor))
                        ,@(if bgcolor   `(:background ,bgcolor))
                        ,@(if bold      '(:bold       t))
                        ,@(if italic    '(:italic     t))
                        ,@(if underline '(:underline  t))))))
           (face (face &rest args)
                 `(,(intern (concat "font-lock-" face "-face"))
                   ,(apply #'color args))))

      (color-theme-install
       `(color-theme-vibi
         ((background-color . ,*background*)
          (background-mode  . dark)
          (border-color     . ,*background*)
          (cursor-color     . ,*cursor*)
          (foreground-color . ,*normal*)
          (mouse-color      . ,*mouse*))
         (default ,(color *normal* *background*))
         (blue ,(color "blue"))
         (border-glyph ((t (nil))))
         (buffers-tab ,(color *normal* *background*))
         ,(face "builtin" *normal*)
         ,(face "comment" *comment*)
         ,(face "constant" *constant*)
         ,(face "doc-string" *string*)
         ,(face "function-name" *method*)
         ,(face "keyword" *keyword*)
         ,(face "preprocessor" *keyword*)
         ,(face "reference" "#99CC99")
         ,(face "regexp-grouping-backslash" *red*)
         ,(face "regexp-grouping-construct" *red*)
         ,(face "string" *string*)
         ,(face "type" *class*)
         ,(face "variable-name" *variable*)
         ,(face "warning" "white" *red*)
         
         (gui-element ,(color *background* "#D4D0C8"))
         (region ,(color nil *region*))
         (mode-line ,(color *background* "grey75"))
         (highlight ,(color nil *current-line*))
         (highline-face ,(color nil *current-line*))
         (italic ((t (nil))))
         (left-margin ((t (nil))))
         (text-cursor ,(color *background* "yellow"))
         (toolbar ((t (nil))))
         (bold ((t (:bold t))))
         (bold-italic ((t (:bold t))))
         (underline ((nil (:underline nil))))

         (rainbow-delimiters-depth-1-face ,(color vibrant-yellow))
         (rainbow-delimiters-depth-2-face ,(color vibrant-purple))
         (rainbow-delimiters-depth-3-face ,(color vibrant-green))
         (rainbow-delimiters-depth-4-face ,(color vibrant-red))
         (rainbow-delimiters-depth-5-face ,(color vibrant-blue))
         (rainbow-delimiters-depth-6-face ,(color vibrant-fg))
         (rainbow-delimiters-depth-7-face ,(color vibrant-purple-1))
         (rainbow-delimiters-depth-8-face ,(color vibrant-red-1))
         (rainbow-delimiters-depth-9-face ,(color vibrant-yellow-1))
         (rainbow-delimiters-depth-10-face ,(color vibrant-green-1))
         (rainbow-delimiters-depth-11-face ,(color vibrant-blue-1))
         (rainbow-delimiters-depth-12-face ,(color vibrant-fg-1))
         (rainbow-delimiters-unmatched-face ((((background dark)) (:foreground "#88090B" :box (:line-width 2 :color "red" :style released-button))))))))))

(provide 'color-theme-vibi)
(color-theme-vibi)
