exec-once = ~/.config/waybar/waybar.sh
exec-once = 1password --ozone-platform-hint=x11  &
exec-once = wl-paste --type text --watch cliphist store &
exec-once = wl-paste --type image --watch cliphist store &

# I think these have to start after hyprland, but I just start it from terminal login. sooooo...
exec-once = systemctl --user restart elephant.service
exec-once = systemctl --user restart walker.service