# Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrule {
    name = jetbrains-splash
    match:class = ^(jetbrains-.*)$
    match:title = ^(splash)$
    match:float = 1
    tag = +jetbrains-splash
    center = on
    no_focus = on
    border_size = 0
}

# Center popups/find windows
# make SURE `input.mouse_refocus = false` otherwise you're in for a bad time
#windowrule {
#    name = jetbrains-popup
#    match:class = ^(jetbrains-.*)
#    match:title = ^()$
#    tag = +jetbrains
#    center = on
#    min_size = (monitor_w*0.5) (monitor_h*0.5)
#}
#windowrule {
#    name = jetbrains-paste-popup
#    match:class = ^(jetbrains-.*)
#    match:title = ^(paste)$
#    tag = +jetbrains
#    center = on
#    min_size = (monitor_w*0.5) (monitor_h*0.5)
#}

## Disable window flicker when autocomplete or tooltips appear
#windowrule {
#    name = jetbrains-tooltip
#    match:class = ^(jetbrains-.*)$
#    match:title = ^(win.*)$
#    match:float = 1
#    no_initial_focus = on
#}