[project]
name = "bin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3",
    "click",
    "dateparser>=1.2.0",
    "pyinstrument>=5.0.0",
    "rich",
]
