#!/bin/sh

## requires emacsclient to be on the path like: ln -s /Applications/Emacs.app/Contents/MacOS/bin/emacsclient ~/.bin
which osascript > /dev/null 2>&1 && osascript -e 'tell application "Emacs" to activate'
emacsclient -c "$@"